### ISSUE TITLE
wrong password saved

### ISSUE THREAD

**Issue by goatguy2310** [TheAimless/learning_python#3]
seems like the app saved the dots, not the actual password
![image](https://user-images.githubusercontent.com/52200386/167164365-f38a0c95-7e6b-467b-ae2b-e084cb80a5d0.png)

**Comment by TheAimless** [comment]
So apparently I used the wrong value for setEchoMode(), as it should be QLineEdit.PasswordEchoOnEdit and not QLineEdit.Password.

**Comment by TheAimless** [comment]
Fixed
